apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejss
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejss
    app.kubernetes.io/part-of: purple-mermaid-app
  name: nodejss
  namespace: kkanova
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejss
    weight: 100
status: {}
